### ISSUE TITLE
Ask about TabLayout.

### ISSUE THREAD

**Issue by WORLD8848** [OneUIProject/oneui-design#1]
Do you not support TabLayout that was available in the previous version?

I am inquiring because I cannot check the oneui-design app with a sample.

**Comment by salvogiangri** [comment]
You can find it in the material module of the sesl lib:
```groovy
implementation 'io.github.oneuiproject.sesl:material:1.0.0'
```

This lib has a "MarginsTabLayout" widget that differs from the original one just for the added padding on the sides.

To summarize: the sesl libs are a clone of Google libraries, that's where you find all the core components/widgets. This design lib instead has all the previous custom view/widgets that are made by us and that you can't find in the Google libraries (ex. ToolbarLayout)
