### ISSUE TITLE
AppBarLayout Height

### ISSUE THREAD

**Issue by WORLD8848** [OneUIProject/oneui-design#10]
I would like to change AppBar Layout Height in oneui-design sample project.

I want to know how to handle it dynamically or XML.

**Comment by salvogiangri** [comment]
Take a look at our [AppBarLayout docs](https://oneuiproject.github.io/sesl/material/appbarlayout/): you can either use `app:seslUseCustomHeight="true"` along with `app:seslHeightProportion` (it should be a float value with a range of 0 to 1) if you want to set it via XML, or `seslSetCustomHeightProportion`/`seslSetCustomHeight` if you want to set it programmatically.
