### ISSUE TITLE
HorizontalRadioPreference android:dependency attribute not working properly

### ISSUE THREAD

**Issue by tribalfs** [OneUIProject/oneui-design#12]
When android:dependency attribute is set on HorizontalRadioPreference, the preference color state disables but the preference is still clickable/enabled.

**Comment by tribalfs** [comment]
<PreferenceCategory>

        <dev.oneuiproject.oneui.preference.HorizontalRadioPreference
            android:key="dark_mode"
            android:title="Dark mode settings"
            app:entries="@array/preferences_darkmode_entries"
            app:entriesImage="@array/preferences_darkmode_entries_image"
            app:entryValues="@array/preferences_darkmode_values"
            android:dependency="dark_mode_auto"
            app:viewType="image" />

        <SwitchPreferenceCompat
            android:key="dark_mode_auto"
            android:title="System default"
            android:disableDependentsState="true"/>

    </PreferenceCategory>

**Comment by tribalfs** [comment]
also tried app:dependency but same issue

**Comment by Yanndroid** [comment]
Fixed by @BlackMesa123 in 1fe67678e4e25b4e3d49ec2834c1f28497b7425e . Thanks for reporting.
