### ISSUE TITLE
Error when setting app:viewType="noImage" attribute in HorizontalRadioPreference

### ISSUE THREAD

**Issue by tribalfs** [OneUIProject/oneui-design#14]
This causes a null array error.
Bug tested by [LeeXDA21](https://github.com/LeeXDA21) in his app.
![image](https://user-images.githubusercontent.com/65062033/209551818-049450ea-208a-406e-be3b-b97fd0df883c.png)

**Comment by tribalfs** [comment]
Might not be a bug.
It's looking for app:entriesSubtitle when "noImage" is set.
If by design, it will be great to add this to the javadoc.

**Comment by salvogiangri** [comment]
Yes, take a look at the old documentation for this preference ([https://github.com/OneUIProject/OneUI-Design-Library/wiki/Preferences#horizontalradiopreference](https://github.com/OneUIProject/OneUI-Design-Library/wiki/Preferences#horizontalradiopreference))

**Comment by tribalfs** [comment]
I see. Maybe we can add that it is as a **required** attribute for noImage
