### ISSUE TITLE
How to Hide Voice Search button?

### ISSUE THREAD

**Issue by ghost1372** [OneUIProject/oneui-design#16]
is it possible to hide Voice button in Search?
![Untitled](https://user-images.githubusercontent.com/9213496/211147188-67bc60e9-518e-4583-96b5-5c2408cd7a3b.png)

**Comment by salvogiangri** [comment]
As per Android documentation [(here)](https://developer.android.com/develop/ui/views/search/search-dialog), remove the searchable configuration and ACTION_SEARCH intent in AndroidManifest.
