### ISSUE TITLE
change font

### ISSUE THREAD

**Issue by ghost1372** [OneUIProject/oneui-design#18]
is it possible to change font for following elements?

<dev.oneuiproject.oneui.preference.TipsCardPreference
<dev.oneuiproject.oneui.preference.HorizontalRadioPreference
        <SwitchPreferenceCompat
        <SeslSwitchPreferenceScreen
        <CheckBoxPreference
        <EditTextPreference
        <ListPreference
        <DropDownPreference
        <MultiSelectListPreference

**Comment by salvogiangri** [comment]
Either use a custom `android:layout` for each Preference or use a custom style for the `textAppearanceListItem` and `android:textAppearanceSmall` attr in your app theme.

**Comment by salvogiangri** [comment]
You can also check this [StackOverflow question](https://stackoverflow.com/questions/13193405/set-custom-font-for-text-in-preferencescreen), it provides some alternative solutions.
