### ISSUE TITLE
how to change application color?

### ISSUE THREAD

**Issue by ghost1372** [OneUIProject/oneui-design#19]
in previous sample app i can see that we can change application color with color picker, but in new sample we cant, can you teach me how to change application color with ColorPickerPreference?
```
<dev.oneuiproject.oneui.preference.ColorPickerPreference
            android:key="colorPicker"
            android:title="رنگ برنامه"
            android:summary="تغییر رنگ برنامه"
            android:defaultValue="#0381FE"
            app:showAlphaSlider="true" />
```

and this

```
override fun onPreferenceChange(preference: Preference?, newValue: Any?): Boolean {
        
        val colorPicker = findPreference<Preference>("colorPicker") as ColorPickerPreference?
        when (preference!!.key) {
           
            "colorPicker" ->{
            }
        }
        return false
    }
```

how we can save and load color?

**Comment by salvogiangri** [comment]
In the old lib this was achieved thanks to the [ThemeUtils](https://github.com/OneUIProject/OneUI-Design-Library/blob/master/yanndroid/oneui/src/main/java/de/dlyt/yanndroid/oneui/utils/ThemeUtil.java) class, we didn't implement it in the new libs since it wasn't a great way to customize the app's theme (too "hacky"). My suggestion for you is to keep the stock theme since all the Samsung apps since One UI 4 use the default blue accent rather than each one having a custom one, but if you still wish to change the main accent you can create a custom theme in your app by replacing the `colorPrimary` and `colorPrimaryDark` attributes.

**Comment by ghost1372** [comment]
Thanks but my main question is how to use ColorPickerPreference in new library.
How should i get color?

**Comment by salvogiangri** [comment]
It works the same as a normal [Preference](https://developer.android.com/reference/androidx/preference/package-summary), so the value is stored in SharedPreferences in the key you've set to the preference item via xml. To get the color value programmatically just cast `newValue` to int.

**Comment by ghost1372** [comment]
i want to save color from colorpicker but i cant i get an error

```
val colorPicker = findPreference<ColorPickerPreference>("colorPicker")
        colorPicker!!.onPreferenceChangeListener = this
```

`Cannot access 'androidx.picker3.app.SeslColorPickerDialog.OnColorSetListener' which is a supertype of 'dev.oneuiproject.oneui.preference.ColorPickerPreference'. Check your module classpath for missing or conflicting dependencies`

**Comment by salvogiangri** [comment]
Please show the whole code, the error is probably somewhere else (you should also see the exact line where the error is).

**Comment by ghost1372** [comment]
i uploaded my codes here
https://github.com/ghost1372/Circulars-OneUI-Test

please take a look.
i have a ColorPickerPreference in a prefrences.xml file and i need to get color value in PrefrencesFragment

**Comment by salvogiangri** [comment]
I can't see the code you're talking about in there, the only reference of the ColorPickerPreference is in the `onPreferenceChange` which hasn't been set for that preference. As I told you `newValue` must be casted to int and not to a String, also [`Color.red`](https://developer.android.com/reference/android/graphics/Color#red(int)), [`Color.green`](https://developer.android.com/reference/android/graphics/Color#green(int)) and [`Color.blue`](https://developer.android.com/reference/android/graphics/Color#blue(int)) all require a color int.

**Comment by ghost1372** [comment]
> I can't see the code you're talking about in there, the only reference of the ColorPickerPreference is in the `onPreferenceChange` which hasn't been set for that preference. As I told you `newValue` must be casted to int and not to a String, also [`Color.red`](https://developer.android.com/reference/android/graphics/Color#red(int)), [`Color.green`](https://developer.android.com/reference/android/graphics/Color#green(int)) and [`Color.blue`](https://developer.android.com/reference/android/graphics/Color#blue(int)) all require a color int.

i forget to add my codes sorry, i updated it again please check.

i added 
```
val colorPicker = findPreference<ColorPickerPreference>("colorPicker")
        colorPicker!!.onPreferenceChangeListener = this
```
in initPreferences method
also i added this code in `override fun onPreferenceChange(preference: Preference?, newValue: Any?): Boolean {` method

```
"colorPicker" -> {
                val selectedColor = newValue.toString().toInt()
                ThemeUtils.setColor(activity as AppCompatActivity, Color.red(selectedColor), Color.green(selectedColor), Color.blue(selectedColor))
                Log.d("LOHH", selectedColor.toString() );
                Log.d("LOHH", Color.red(selectedColor).toString() );
                return true
            }
```
i have error in colorPicker!!.onPreferenceChangeListener = this


i casted newValue to Int ====> val selectedColor = newValue.toString().toInt()

**Comment by salvogiangri** [comment]
You clearly forgot to add the picker-color dependency in your app:
```groovy
implementation 'io.github.oneuiproject.sesl:picker-color:1.0.1'
```

I'm not an expert of Kotlin but I think the best way to cast `newValue` to int is this since afaik Kotlin is really strict about nullable objects:
```kotlin
val selectedColor = newValue as? Int ?: Color.BLACK
```

**Comment by ghost1372** [comment]
tnx issue fixed😁
