### ISSUE TITLE
Change Application Accent Color in Runtime

### ISSUE THREAD

**Issue by ghost1372** [OneUIProject/oneui-design#20]
Hi, sorry for more questions 😁
i am trying to change application accent color, i can read color from ColorPicker and Save it in Prefrences. its OK.
but i am using this codes in MainActivity for changing application accent color before onCreate method.

```

val sharedPreferences = getSharedPreferences("ThemeColor", Context.MODE_PRIVATE)
        val stringColor = sharedPreferences.getString("color", "0381fe")

// stringColor output is: e100e1
        setTheme(resources.getIdentifier("Color_$stringColor", "style", packageName))
```

i can see that stringColor  is changed and set to new color but after using setTheme nothing happened and i cant see new color.

where is wrong? i am copied this codes from yours old library.

**Comment by salvogiangri** [comment]
You also need to add the styles.xml file with all the defined themes in your app ([https://github.com/OneUIProject/OneUI-Design-Library/blob/master/yanndroid/oneui/src/main/res/values-v9/styles.xml](https://github.com/OneUIProject/OneUI-Design-Library/blob/master/yanndroid/oneui/src/main/res/values-v9/styles.xml)).

**Comment by ghost1372** [comment]
thanks.
in values folder or values-v9?

**Comment by ghost1372** [comment]
Thank you @BlackMesa123 
i added styles in values-v9 folder. in emulator everything is working fine, but in my A51 Device (Android 13/OneUI 5) SwitchPreferenceCompat and androidx.appcompat.widget.SeslSwitchBar color is not changed

**Comment by salvogiangri** [comment]
> Thank you @BlackMesa123 
> 
> i added styles in values-v9 folder. in emulator everything is working fine, but in my A51 Device (Android 13/OneUI 5) SwitchPreferenceCompat and androidx.appcompat.widget.SeslSwitchBar color is not changed 

You might have to set a custom style for SwitchCompat and SeslSwitchBar in your theme in order to match the color you want.
