### ISSUE TITLE
About title of PrefrenceFragment in DrawerLayout

### ISSUE THREAD

**Issue by long266** [OneUIProject/oneui-design#3]
As title, I have setup a NavigationView, with 4 PreferenceFragmentCompat as 4 fragments
All is working flawlessly until I realized that all 4 fragments have the same title
Removing `app:title` from root layout, obviously no title
Tried some stuff like
`getActivity().setTitle(title);`
but no luck
So, how can I add title to PreferenceFragment in DrawerLayout. Thanks !
Here is my code: [MainActivity](https://github.com/long266/Lumi-Constellation/blob/main/app/src/main/java/com/nhlong/lumi/constellation/LumiMainActivity.java)
![image](https://user-images.githubusercontent.com/71440530/172201143-c522a770-1759-47c5-9315-ce54f3c59e43.png)

**Comment by salvogiangri** [comment]
Both DrawerLayout and ToolbarLayout have methods to manage the AppBar Title and Subtitle:
`drawerLayout.setTitle(title)`
`drawerLayout.setTitle(expandedTitle, collapsedTitle)`
`drawerLayout.setExpandedSubtitle(expandedSubtitle)`
`drawerLayout.setCollapsedSubtitle(collapsedSubtitle)`

**Comment by long266** [comment]
> Both DrawerLayout and ToolbarLayout have methods to manage the AppBar Title and Subtitle: `drawerLayout.setTitle(title)` `drawerLayout.setTitle(expandedTitle, collapsedTitle)` `drawerLayout.setExpandedSubtitle(expandedSubtitle)` `drawerLayout.setCollapsedSubtitle(collapsedSubtitle)`

I know that but where should I add it

**Comment by salvogiangri** [comment]
Where you want depending your needs. If you want the title to change every time your drawer selected item changes you should consider adding a listener in your drawer and changing the title in there

**Comment by long266** [comment]
Thank you! Problem solved
