### ISSUE TITLE
Please manage the version of oneui-design.

### ISSUE THREAD

**Issue by WORLD8848** [OneUIProject/oneui-design#5]
Please manage the version of oneui-design.

**Comment by Yanndroid** [comment]
Wdym?

**Comment by WORLD8848** [comment]
Whenever oneui-design is updated, I think it would be better to operate the tag or release version.

**Comment by Yanndroid** [comment]
The latest version available right now is 1.0.0 and the library is only on Maven, we probably won't add it to github releases.

**Comment by WORLD8848** [comment]
Thank you for the information that github release is not used.

Additionally, I would like to ask you to share how to check the version on Maven.

**Comment by Yanndroid** [comment]
There will be a badge in the readme (like in oneui-core)
[![](https://img.shields.io/maven-central/v/io.github.oneuiproject/design?color=%23C71A36&logoColor=%23C11920&style=flat-square)](https://mvnrepository.com/artifact/io.github.oneuiproject/design)

**Comment by WORLD8848** [comment]
I was able to find version information of 1.0.0 in ReadMe.

Thank you.

![image](https://user-images.githubusercontent.com/65061404/175019580-269c2cd8-2d80-4211-9933-e5904740e6e4.png)
